=== el-X/convex3d-earth/xsd/countries.xsd
<?xml version="1.0"?>
<!--
The XML Schema Defintion for the country dataset is defined here.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <!-- ### Simple Types ### -->
    <xs:simpleType name="countryIdType">
        <xs:restriction base="xs:ID">
            <xs:pattern value="[A-Z]{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nameType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:pattern value="[^0-9]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="continentType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Africa"/>
            <xs:enumeration value="Antarctica"/>
            <xs:enumeration value="Asia"/>
            <xs:enumeration value="Europe"/>
            <xs:enumeration value="North America"/>
            <xs:enumeration value="South America"/>
            <xs:enumeration value="Oceania"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="latitudeType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="-90"/>
            <xs:maxInclusive value="90"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="longitudeType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="-180"/>
            <xs:maxInclusive value="180"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- ### Complex Types ### -->
    <xs:element name="countries" type="countriesType"/>

    <!-- Countries -->
    <xs:complexType name="countriesType">
        <xs:sequence>
            <xs:element name="country" type="countryType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Country -->
    <xs:complexType name="countryType">
        <xs:sequence>
            <xs:element name="name" type="nameType"/>
            <xs:element name="continent" type="continentType"/>
            <xs:element name="northLatitude" type="latitudeType"/>
            <xs:element name="southLatitude" type="latitudeType"/>
            <xs:element name="westLongitude" type="longitudeType"/>
            <xs:element name="eastLongitude" type="longitudeType"/>
            <xs:element name="capital" type="capitalType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="countryIdType" use="required"/>
    </xs:complexType>

    <!-- Capital -->
    <xs:complexType name="capitalType">
        <xs:sequence>
            <xs:element name="name" type="nameType"/>
            <!-- "wikiName" is used as an alternative search string -->
            <!-- whenever "name" fails to deliver proper results    -->
            <xs:element name="wikiName" type="nameType" minOccurs="0"/>
            <xs:element name="latitude" type="latitudeType"/>
            <xs:element name="longitude" type="longitudeType"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== el-X/convex3d-earth/data/countries.xml
<?xml version="1.0" encoding="UTF-8"?>

<countries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="./xsd/countries.xsd">
    <country id="AD">
        <name>Andorra</name>
        <continent>Europe</continent>
        <westLongitude>1.4071867141112762</westLongitude>
        <eastLongitude>1.7865427778319827</eastLongitude>
        <northLatitude>42.65604389629997</northLatitude>
        <southLatitude>42.42849259876837</southLatitude>
        <capital id="temp">
            <name>Andorra la Vella</name>
            <longitude>1.3</longitude>
            <latitude>42.3</latitude>
        </capital>
    </country>
    <country id="AE">
        <name>United Arab Emirates</name>
        <continent>Asia</continent>
        <westLongitude>51.58332824707031</westLongitude>
        <eastLongitude>56.38166046142578</eastLongitude>
        <northLatitude>26.08415985107422</northLatitude>
        <southLatitude>22.633329391479492</southLatitude>
        <capital id="temp">
            <name>Abu Dhabi</name>
            <longitude>54.36</longitude>
            <latitude>24.27</latitude>
        </capital>
    </country>
    <country id="AF">
        <name>Afghanistan</name>
        <continent>Asia</continent>
        <westLongitude>60.478443</westLongitude>
        <eastLongitude>74.879448</eastLongitude>
        <northLatitude>38.483418</northLatitude>
        <southLatitude>29.377472</southLatitude>
        <capital id="temp">
            <name>Kabul</name>
            <longitude>69.2</longitude>
            <latitude>34.5833</latitude>
        </capital>
    </country>
    <country id="AG">
        <name>Antigua and Barbuda</name>
        <continent>North America</continent>
        <westLongitude>-61.906425</westLongitude>
        <eastLongitude>-61.672421</eastLongitude>
        <northLatitude>17.729387</northLatitude>
        <southLatitude>16.996979</southLatitude>
        <capital id="temp">
            <name>St. John's</name>
            <longitude></longitude>
            <latitude></latitude>
        </capital>
    </country>
    <country id="AI">
        <name>Anguilla</name>
        <continent>North America</continent>
        <westLongitude>-63.172901</westLongitude>
        <eastLongitude>-62.971359</eastLongitude>
        <northLatitude>18.283424</northLatitude>
        <southLatitude>18.166815</southLatitude>
        <capital id="temp">
            <name>The Valley</name>
            <longitude></longitude>
            <latitude></latitude>
        </capital>
    </country>
    <country id="AL">
        <name>Albania</name>
        <continent>Europe</continent>
        <westLongitude>19.293972</westLongitude>
        <eastLongitude>21.068472</eastLongitude>
        <northLatitude>42.665611</northLatitude>
        <southLatitude>39.648361</southLatitude>
        <capital id="temp">
            <name>Tirana</name>
            <longitude></longitude>
            <latitude></latitude>
        </capital>
    </country>
    <country id="AM">
        <name>Armenia</name>
        <continent>Asia</continent>
        <westLongitude>43.44978</westLongitude>
        <eastLongitude>46.772435045159995</eastLongitude>
        <northLatitude>41.301834</northLatitude>
        <southLatitude>38.830528</southLatitude>
        <capital id="temp">
            <name>Yerevan</name>
            <longitude></longitude>
            <latitude></latitude>
        </capital>
    </country>
    <country id="AO">
        <name>Angola</name>
        <continent>Africa</continent>
        <westLongitude>11.679219</westLongitude>
        <eastLongitude>24.082119</eastLongitude>
        <northLatitude>-4.376826</northLatitude>
        <southLatitude>-18.042076</southLatitude>
        <capital id="temp">
            <name>Luanda</name>
            <longitude></longitude>
            <latitude></latitude>
        </capital>
    </country>
    <country id="AQ">
        <name>Antarctica</name>
        <continent>Antarctica</continent>
        <westLongitude>-179.9999</westLongitude>
        <eastLongitude>179.9999</eastLongitude>
        <northLatitude>-60.515533</northLatitude>
        <southLatitude>-89.9999</southLatitude>
    </country>
    <country id="AR">
        <name>Argentina</name>
        <continent>South America</continent>
        <westLongitude>-73.58297</westLongitude>
        <eastLongitude>-53.591835</eastLongitude>
        <northLatitude>-21.781277</northLatitude>
        <southLatitude>-55.061314</southLatitude>
        <capital id="temp">
            <name>Buenos Aires</name>
            <longitude></longitude>
            <latitude></latitude>
        </capital>
    </country>
    <country id="AS">
        <name>American Samoa</name>
        <continent>Oceania</continent>
        <westLongitude>-171.091888</westLongitude>
        <eastLongitude>-169.416077</eastLongitude>
        <northLatitude>-11.0497</northLatitude>
        <southLatitude>-14.382478</southLatitude>
        <capital id="temp">
            <name>Pago Pago</name>
            <longitude></longitude>
            <latitude></latitude>
        </capital>
    </country>
    <country id="AT">
        <name>Austria</name>
        <continent>Europe</continent>
        <westLongitude>9.53095237240833</westLongitude>
        <eastLongitude>17.1620685652599</eastLongitude>
        <northLatitude>49.0211627691393</northLatitude>
        <southLatitude>46.3726520216244</southLatitude>
        <capital id="temp">
            <name>Vienna</name>
            <longitude></longitude>
            <latitude></latitude>
        </capital>
    </country>
    <country id="AU">
        <name>Australia</name>
        <continent>Oceania</continent>
        <westLongitude>112.911057</westLongitude>
        <eastLongitude>153.639252</eastLongitude>
        <northLatitude>-10.062805</northLatitude>
        <southLatitude>-43.64397</southLatitude>
        <capital id="temp">
            <name>Canberra</name>
            <longitude></longitude>
            <latitude></latitude>
        </capital>
    </country>
    <country id="AW">
        <name>Aruba</name>
        <continent>North America</continent>
        <westLongitude>-70.0644737196045</westLongitude>
        <eastLongitude>-69.86575120104982</eastLongitude>
        <northLatitude>12.623718127152925</northLatitude>
        <southLatitude>12.411707706190716</southLatitude>
        <capital id="temp">
            <name>Oranjestad</name>
            <longitude></longitude>
            <latitude></latitude>
        </capital>
    </country>
    <country id="AX">
        <name>Ã…land</name>
        <continent>Europe</continent>
        <westLongitude>19.317694</westLongitude>
        <eastLongitude>21.011862</eastLongitude>
        <northLatitude>60.488861</northLatitude>
        <southLatitude>59.90675</southLatitude>
        <capital id="temp">
            <name>Mariehamn</name>
            <longitude></longitude>
            <latitude></latitude>
        </capital>
    </country>
    <country id="AZ">
        <name>Azerbaijan</name>
        <continent>Asia</continent>
        <westLongitude>44.774113</westLongitude>
        <eastLongitude>50.370083</eastLongitude>
        <northLatitude>41.90564</northLatitude>
        <southLatitude>38.38915252685547</southLatitude>
        <capital id="temp">
            <name>Baku</name>
            <longitude></longitude>
            <latitude></latitude>
        </capital>
    </country>
    <country id="BA">
        <name>Bosnia and Herzegovina</name>
        <continent>Europe</continent>
        <westLongitude>15.718945</westLongitude>
        <eastLongitude>19.622223</eastLongitude>
        <northLatitude>45.239193</northLatitude>
        <southLatitude>42.546112</southLatitude>
        <capital id="temp">
            <name>Sarajevo</name>
            <longitude></longitude>
            <latitude></latitude>
        </capital>
    </country>
    <country id="BB">
        <name>Barbados</name>
        <continent>North America</continent>
        <westLongitude>-59.648922</westLongitude>
        <eastLongitude>-59.420376</eastLongitude>
        <northLatitude>13.327257</northLatitude>
        <southLatitude>13.039844</southLatitude>
        <capital id="temp">
            <name>Bridgetown</name>
            <longitude></longitude>
            <latitude></latitude>
        </capital>
    </country>
    <country id="BD">
        <name>Bangladesh</name>
        <continent>Asia</continent>
        <westLongitude>88.028336</westLongitude>
        <eastLongitude>92.673668</eastLongitude>
        <northLatitude>26.631945</northLatitude>
        <southLatitude>20.743334</southLatitude>
        <capital id="temp">
            <name>Dhaka</name>
            <longitude></longitude>
            <latitude></latitude>
        </capital>
    </country>
    <country id="BE">
        <name>Belgium</name>
        <continent>Europe</continent>
        <westLongitude>2.546944</westLongitude>
        <eastLongitude>6.403861</eastLongitude>
        <northLatitude>51.505444</northLatitude>
        <southLatitude>49.49361</southLatitude>
        <capital id="temp">
            <name>Brussels</name>
            <longitude></longitude>
            <latitude></latitude>
        </capital>
    </country>
    <country id="BF">
        <name>Burkina Faso</name>
        <continent>Africa</continent>
        <westLongitude>-5.518916</westLongitude>
        <eastLongitude>2.405395</eastLongitude>
        <northLatitude>15.082593</northLatitude>
        <southLatitude>9.401108</southLatitude>
        <capital id="temp">
            <name>Ouagadougou</name>
            <longitude></longitude>
            <latitude></latitude>
        </capital>
    </country>
    <country id="BG">
        <name>Bulgaria</name>
        <continent>Europe</continent>
        <westLongitude>22.371166</westLongitude>
        <eastLongitude>28.612167</eastLongitude>
